---
# Directory
watchtower_dir: "{{ infra_root }}/watchtower"

# Image
watchtower_image: "containrrr/watchtower:latest"
watchtower_container: "watchtower"

# Check interval in seconds
watchtower_interval: 300

# Remove old images after update
watchtower_cleanup: true

# Only update containers with the watchtower label
watchtower_label_enable: true

# Send notification on update
watchtower_notifications: false
watchtower_notification_url: ""