---
- name: 📦 Installation system dependencies
  ansible.builtin.apt:
    name:
      - curl
      - git
      - ca-certificates
      - gnupg
      - python3-pip
    state: present
    update_cache: true

- name: 🐳 Vérifier si Docker est installé
  command: docker --version
  register: docker_installed
  ignore_errors: true
  changed_when: false

- name: 🐳 Installer Docker si absent
  include_tasks: install.yml
  when: docker_installed.failed

- name: 🐳 Vérifier la version Docker
  debug:
    msg: "Docker version : {{ docker_installed.stdout }}"
    
- name: 🌐 Create shared Docker network
  community.docker.docker_network:
    name: "{{ docker_network_name }}"
    state: present