---
- name: 📦 Installation system dependencies
  ansible.builtin.apt:
    name:
      - curl
      - git
      - ca-certificates
      - gnupg
      - python3-pip
    state: present
    update_cache: true

- name: 🐳 Verify if Docker is installed
  command: docker --version
  register: docker_installed
  ignore_errors: true
  changed_when: false

- name: 🐳 Install Docker if absent
  include_tasks: install.yml
  when: docker_installed.failed

- name: 🐳 Verify Docker version
  debug:
    msg: "Docker version : {{ docker_installed.stdout }}"

- name: 🌐 Create shared Docker network
  community.docker.docker_network:
    name: "{{ docker_network_name }}"
    state: present